2025/03/03 18:04:10 [error] 29#29: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: practical_assessment, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "localhost"
2025/03/03 18:04:15 [error] 29#29: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: practical_assessment, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "localhost"
2025/03/03 18:04:36 [error] 29#29: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: practical_assessment, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "localhost"
2025/03/03 18:08:26 [error] 29#29: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: practical_assessment, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2025/03/03 18:08:31 [error] 29#29: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: practical_assessment, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
